name: 02 - Eventos
on:   
  pull_request:
  schedule:
    - cron: '44 * * * *'
  workflow_dispatch: 

jobs:
  echo: 
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: | 
            echo "Event name: ${{ github.event_name }}"    