name: 02 - Eventos
on: 
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  echo: 
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: "Event name: ${{ github.event_name }}"    