name: Ejemplo Curso CI
run-name: Mi WF Manual
on:  
  push: 
    branches: 
      - features
      - other
  pull_request: 
    branches: main
    types: [opened, synchronize]
  workflow_dispatch:   
    inputs:
      debug: 
        type: boolean
        description: Quiero Depurar?
        default: false
      environment:
        type: choice
        description: Entorno
        options:            
           - int
           - pre
           - prod
      addParams:
        type: string
        description: Parametros adicionales
        default: "default Pram"


          
      
jobs:
  build: 
    runs-on: ubuntu-latest
    name: ${{github }}
    defaults:
      run:
        working-directory: app-test
    steps:
      - name: Descargar codigo ${{runner.name }}

        uses: actions/checkout@v4

      - name: Configurar node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: install deps
        run: npm ci        

      - name: Run tests deps
        run: npm test        
