name: CI Node
on: push

jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-test
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: install deps
        run: npm ci        

      - name: Run tests deps
        run: npm test        
